ZO_CreateStringId("SI_CBE_CRAFTBAG_MAIL_DETACH", 
    GetString(SI_ITEM_ACTION_MAIL_DETACH) .. GetString(SI_CBE_AND) .. GetString(SI_ITEM_ACTION_ADD_ITEMS_TO_CRAFT_BAG))
ZO_CreateStringId("SI_CBE_CRAFTBAG_MAIL_ATTACH", 
    GetString(SI_ITEM_ACTION_REMOVE_ITEMS_FROM_CRAFT_BAG) .. GetString(SI_CBE_AND) .. GetString(SI_ITEM_ACTION_MAIL_ATTACH))
ZO_CreateStringId("SI_CBE_CRAFTBAG_BANK_DEPOSIT", 
    GetString(SI_ITEM_ACTION_REMOVE_ITEMS_FROM_CRAFT_BAG) .. GetString(SI_CBE_AND) .. GetString(SI_ITEM_ACTION_BANK_DEPOSIT))